# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [53]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [105]:
citiesDF = pd.read_csv("../output_data/cities.csv")
cities_csv.head(2)

,Unnamed: 0,City,Lat,Long,Max Temp (F),Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Pevek,69.7008,170.3133,36.10,88,58,0.85,RU,1658685924
1,1,Jamestown,42.0970,-79.2353,84.94,71,75,9.22,US,1658685925

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [56]:
# Configure Locations and Weights
locations = citiesDF[['Lat', 'Long']]
weight = citiesDF['Humidity'].astype(float)

# Configure gmap
gmaps.configure(api_key=g_key)

# Plot Heatmap
fig = gmaps.figure()

# add a marker latyer on heatmap
marker_layer = gmaps.marker_layer(locations)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=weight, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [57]:
citiesDF

,Unnamed: 0,City,Lat,Long,Max Temp (F),Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Pevek,69.7008,170.3133,36.10,88,58,0.85,RU,1658685924
1,1,Jamestown,42.0970,-79.2353,84.94,71,75,9.22,US,1658685925
2,2,Cape Town,-33.9258,18.4232,59.38,69,0,11.99,ZA,1658685902
3,3,Iskateley,67.6803,53.1512,51.31,75,100,9.19,RU,1658685926
4,4,Provideniya,64.3833,-173.3000,42.53,87,100,5.12,RU,1658685434
...,...,...,...,...,...,...,...,...,...,...
570,570,Mossendjo,-2.9506,12.7261,76.41,63,95,2.48,CG,1658686111
571,571,Kununurra,-15.7667,128.7333,49.98,81,4,0.00,AU,1658686111
572,572,Great Yarmouth,52.6083,1.7305,82.65,36,23,18.52,GB,1658686111
573,573,Acapulco de Juárez,16.8634,-99.8901,87.62,66,40,6.91,MX,1658686112
574,574,Barentu,15.1139,37.5928,68.83,82,100,4.05,ER,1658686112

In [58]:
# The perfect weather conditions! (Drop all rows that doesnt satisfy conditions):
# Humidity < 60
# Temp: < 85 and > 70
# Cloudiness < 40

citiesDF.drop(citiesDF[citiesDF["Humidity"] > 60].index, inplace= True)
citiesDF.drop(citiesDF[(citiesDF["Max Temp (F)"] < 70) | (citiesDF["Max Temp (F)"] > 85)].index, inplace= True)
citiesDF.drop(citiesDF[citiesDF["Cloudiness"] > 40].index, inplace= True)
citiesDF

,Unnamed: 0,City,Lat,Long,Max Temp (F),Humidity,Cloudiness,Wind Speed,Country,Date
48,48,Den Helder,52.9599,4.7593,79.99,58,40,11.99,NL,1658685937
76,76,Sechura,-5.5569,-80.8222,77.29,58,19,12.73,PE,1658685945
141,141,Giraltovce,49.1140,21.5173,75.15,53,25,5.97,SK,1658685962
271,271,Malinyi,-8.9333,36.1333,72.79,52,33,1.92,TZ,1658686003
281,281,Spencer,43.1414,-95.1444,80.71,53,0,13.80,US,1658685793
307,307,Margate,51.3813,1.3862,80.87,58,13,5.99,GB,1658685500
323,323,Adana Province,36.9850,35.2881,82.92,57,0,4.61,TR,1658686024
324,324,San Jose,37.3394,-121.8950,81.82,45,0,4.61,US,1658685727
337,337,Kirando,-7.4167,30.6000,75.60,53,8,1.16,TZ,1658686029
375,375,Porto Santo,33.0720,-16.3415,80.98,54,20,14.97,PT,1658686042
413,413,Lata,40.1629,-8.3327,76.08,39,29,8.03,PT,1658685533
421,421,Los Alamos,35.8881,-106.3070,80.94,46,40,6.91,US,1658686057
435,435,Abancay,-13.6339,-72.8814,75.22,33,30,6.38,PE,1658686062
463,463,Aktau,43.6500,51.2000,70.38,58,22,13.56,KZ,1658686072
485,485,Medford,42.3265,-122.8756,82.60,44,0,3.44,US,1658685801
494,494,Vila,42.0304,-8.1588,75.70,50,7,6.51,PT,1658685790
520,520,Gotha,50.9482,10.7019,84.85,35,0,5.75,DE,1658686092
572,572,Great Yarmouth,52.6083,1.7305,82.65,36,23,18.52,GB,1658686111

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [88]:
# Store citiesDF into hotel_df and add "Hotel Name" column to DataFrame
hotel_df = citiesDF
#hotel_name = []

# Set parameters
#target_coordinates = ""
target_radius = 5000 #(Meters)
target_type = "hotel"

# Dictionary of parameters
parameters = {  
    'radius' : target_radius, 
    'type' : target_type, 
    'key' : g_key
}

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# Request url to test if works
#hotel_response = requests.get(base_url, params = parameters).json()
#hotel_response['results'][1]['name']

# Create for loop to search for hotels in every city in DF
for i, row in hotel_df.iterrows():
    lat = row['Lat']
    long = row['Long']
    
    # Change target coordinates each iteration while leaving other params in place
    parameters['location'] = f'{lat}, {long}'
    
    # Use base_url to search for hotels using coords
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and jsonify
    print(f"Results for Index {i}: {row['City']}.")
    hotelJSON = requests.get(base_url, params= parameters).json()
    
    # Extract results
    results = hotelJSON['results'][1]['name']
    
    # Skip if no hotels are found
    try:
        print(f"Nearest hotel within {target_radius} meters is {results}")
        hotel_df.loc[i, "Hotel Name"] = results
    except (KeyError, IndexError):
        print("No results. Skipping.")
              
    print("--------------------------------")

Results for Index 48: Den Helder.
Nearest hotel within 5000 meters is Hotel Den Helder
--------------------------------
Results for Index 76: Sechura.
Nearest hotel within 5000 meters is Municipalidad Provincial de Sechura
--------------------------------
Results for Index 141: Giraltovce.
Nearest hotel within 5000 meters is Jaroslav Maťaš
--------------------------------
Results for Index 271: Malinyi.
Nearest hotel within 5000 meters is Lugala Lutheran Hospital
--------------------------------
Results for Index 281: Spencer.
Nearest hotel within 5000 meters is Reston Inn & Suites
--------------------------------
Results for Index 307: Margate.
Nearest hotel within 5000 meters is Premier Inn Margate hotel
--------------------------------
Results for Index 323: Adana Province.
Nearest hotel within 5000 meters is Hotel Le Grand
--------------------------------
Results for Index 324: San Jose.
Nearest hotel within 5000 meters is ["Hotel De Anza - Destination by Hyatt"]
--------------------------------
Results for Index 337: Kirando.
Nearest hotel within 5000 meters is White Fathers Monastery
--------------------------------
Results for Index 375: Porto Santo.
Nearest hotel within 5000 meters is Hotel Porto Santo & Spa
--------------------------------
Results for Index 413: Lata.
Nearest hotel within 5000 meters is Casa Maquia
--------------------------------
Results for Index 421: Los Alamos.
Nearest hotel within 5000 meters is Motel 6 Los Alamos NM
--------------------------------
Results for Index 435: Abancay.
Nearest hotel within 5000 meters is Siball Hotel
--------------------------------
Results for Index 463: Aktau.
Nearest hotel within 5000 meters is Silk Way Hotel
--------------------------------
Results for Index 485: Medford.
Nearest hotel within 5000 meters is Rodeway Inn
--------------------------------
Results for Index 494: Vila.
Nearest hotel within 5000 meters is Hotel Castrum Villae by Walk Hotels
--------------------------------
Results for Index 520: Gotha.
Nearest hotel within 5000 meters is Hotel am Schlosspark
--------------------------------
Results for Index 572: Great Yarmouth.
Nearest hotel within 5000 meters is Comfort Hotel Great Yarmouth
--------------------------------

In [92]:
hotel_df.drop(columns= 'Unnamed: 0').head(2)

,City,Lat,Long,Max Temp (F),Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
48,Den Helder,52.9599,4.7593,79.99,58,40,11.99,NL,1658685937,Hotel Den Helder
76,Sechura,-5.5569,-80.8222,77.29,58,19,12.73,PE,1658685945,Municipalidad Provincial de Sechura

In [104]:
locations = hotel_df[["Lat", "Long"]]
markers = gmaps.marker_layer(locations)

# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Long"]]

# Add marker layer ontop of heat map
hotel_layer = gmaps.symbol_layer(locations, info_box_content= hotel_info)

# Display figure
fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig

Figure(layout=FigureLayout(height='420px'))